In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('./Telecom Churn.csv')

In [4]:
df

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [6]:
df.describe()

,account length,area code,number vmail messages,total day minutes,total day calls,total day charge,total eve minutes,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [7]:
import numpy as np
from sklearn.cluster import KMeans

# Given points
points = np.array([[0.1, 0.6], [0.15, 0.71], [0.08, 0.9], [0.16, 0.85],
                   [0.2, 0.3], [0.25, 0.5], [0.24, 0.1], [0.3, 0.2]])

# Initial centroids
m1 = np.array([0.1, 0.6])
m2 = np.array([0.3, 0.2])

# Perform k-means clustering
kmeans = KMeans(n_clusters=2, init=np.array([m1, m2]), n_init=1)
kmeans.fit(points)

# Assign points to clusters
cluster_assignment = kmeans.predict(points)

# 1] Which cluster does P6 belong to?
p6 = np.array([0.25, 0.5])
cluster_p6 = kmeans.predict([p6])[0]
print(f"1] P6 belongs to Cluster #{cluster_p6 + 1}")

# 2] What is the population of a cluster around m2?
population_m2 = np.sum(cluster_assignment == 1)  # Assuming cluster 2 is indexed as 1
print(f"2] Population of Cluster around m2 (C2): {population_m2}")

# 3] What is the updated value of m1 and m2?
updated_m1 = kmeans.cluster_centers_[0]
updated_m2 = kmeans.cluster_centers_[1]
print(f"3] Updated value of m1: {updated_m1}")
print(f"   Updated value of m2: {updated_m2}")

1] P6 belongs to Cluster #1
2] Population of Cluster around m2 (C2): 3
3] Updated value of m1: [0.148 0.712]
   Updated value of m2: [0.24666667 0.2       ]

In [3]:
import numpy as np
from sklearn.cluster import KMeans

In [4]:
points = np.array([[0.1,0.6],[0.15,0.71],[0.08, 0.9], [0.16, 0.85],
                   [0.2, 0.3], [0.25, 0.5], [0.24, 0.1], [0.3, 0.2]])

In [5]:
m1 = np.array([0.1,0.6])
m2 = np.array([0.3,0.2])

In [6]:
kmeans = KMeans(n_clusters = 2, init=np.array([m1,m2]), n_init=1)
kmeans.fit(points)

KMeans(init=array([[0.1, 0.6],
       [0.3, 0.2]]), n_clusters=2, n_init=1)

In [7]:
#assign clusters
clustered = kmeans.predict(points)

In [15]:
p8 = np.array([0.3, 0.2])
cluster_p8 = kmeans.predict([p8])[0]
print(cluster_p8+1)

2

In [17]:
population = np.sum(clustered ==1)
print(population)

3

In [18]:
um1 = kmeans.cluster_centers_[0]
um2 = kmeans.cluster_centers_[1]
print(um1)
print(um2)

[0.148 0.712]
[0.24666667 0.2       ]

In [19]:
import numpy as np
from sklearn.cluster import KMeans

In [20]:
point = np.array([[2,10],[2,5], [8,4], [5,8],[7,5],[6,4],[1,2],[4,9]])

In [22]:
m1 = np.array([2,10])
m2 = np.array([5,8])
m3 = np.array([1,2])

In [24]:
kmeans = KMeans(n_clusters = 3, n_init = 1, init = np.array([m1,m2,m3]))
kmeans.fit(point)

KMeans(init=array([[ 2, 10],
       [ 5,  8],
       [ 1,  2]]), n_clusters=3,
       n_init=1)

In [29]:
cp6 = np.array([6,4])
p6 = kmeans.predict([cp6])[0]
print(p6+1)

2

In [38]:
cluster = kmeans.predict(point)
pm3 = np.sum(cluster == 2)
print(pm3)

2

In [39]:
um1 = kmeans.cluster_centers_[0]
um2 = kmeans.cluster_centers_[1]
um3 = kmeans.cluster_centers_[2]
print(um1)
print(um2)
print(um3)

[3.66666667 9.        ]
[7.         4.33333333]
[1.5 3.5]